services:
  gym_crm_dev_db:
    image: mysql:8.0
    container_name: gym_crm_dev_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gym_crm_dev
    ports:
      - "3307:3306" # Dev MySQL
    networks:
      - springboot_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexample"]
      interval: 10s
      timeout: 5s
      retries: 5

  gym_crm_stg_db:
    image: mysql:8.0
    container_name: gym_crm_stg_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gym_crm_stg
    ports:
      - "3308:3306" # Staging MySQL
    networks:
      - springboot_network

  gym_crm_prod_db:
    image: mysql:8.0
    container_name: gym_crm_prod_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gym_crm_prod
    ports:
      - "3309:3306" # Production MySQL
    networks:
      - springboot_network

  flyway:
    image: flyway/flyway:8.0.4
    container_name: gym-crm-flyway
    depends_on:
      gym_crm_dev_db:
        condition: service_healthy
    environment:
      FLYWAY_URL: jdbc:mysql://gym_crm_dev_mysql:3306/gym_crm_dev?useSSL=false&allowPublicKeyRetrieval=true
      FLYWAY_USER: root
      FLYWAY_PASSWORD: example
      FLYWAY_CONNECT_RETRIES: 10
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    command: migrate
    networks:
      - springboot_network

  cache:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - springboot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - "61616:61616" # JMS
      - "8161:8161"   # Web Console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - activemq-data:/opt/activemq/data
    networks:
      - springboot_network
      - app_common_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5

  gym-crm-app:
    build: .
    container_name: gym-crm-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://gym_crm_dev_mysql:3306/gym_crm_dev?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
      - SPRING_REDIS_HOST=redis
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_VALIDATOR_APPLY_TO_DDL=false
      - EUREKA_CLIENT_ENABLED=false
      - JAVA_OPTS=-Dspring.profiles.active=dev -Djava.security.egd=file:/dev/./urandom
    depends_on:
      cache:
        condition: service_healthy
      activemq:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot_network
      - app_common_network

volumes:
  activemq-data:

networks:
  springboot_network:
    driver: bridge
  app_common_network:
    driver: bridge